GET http://localhost:9090/api/v1/ping

###

GET http://localhost:9090/api/v1/book

###

POST http://localhost:9090/api/v1/book HTTP/1.1
content-type: application/json

{
    "name":"GO Book v2",
	"author":"GOLang 4ever",
	"rating":"5"
}

###

GET http://localhost:9090/api/v1/book/2

###

DELETE http://localhost:9090/api/v1/book/1
